SPECS = {
 "01_quiz2": dict(kind="quiz", music="suspense", title="QUIZ TIME !", sub="5 questions • Compte tes points",
   outro1="Combien sur 5 ?", outro2="Écris ton score\nen commentaire", items=[
   dict(q="« J'ai faim. »", opts=["I have hunger", "I am hungry", "I am hunger"], ok=1, note="Avoir faim = to be hungry"),
   dict(q="« Il ne parle pas anglais. »", opts=["He don't speak English", "He doesn't speaks English", "He doesn't speak English"], ok=2, note="He / She + doesn't + verbe sans -s"),
   dict(q="« Je suis né en 1995. »", opts=["I was born in 1995", "I am born in 1995", "I born in 1995"], ok=0, note="Être né = was born"),
   dict(q="« Elle a les cheveux longs. »", opts=["She has long hairs", "She has long hair", "She have long hair"], ok=1, note="Hair (cheveux) ne prend pas de -s"),
   dict(q="« Ça dépend de toi. »", opts=["It depends on you", "It depends of you", "It depend from you"], ok=0, note="Depend + on (pas « of »)"),
 ]),
 "02_ordre": dict(kind="order", music="energie", title="REMETS DANS\nL'ORDRE !", sub="5 phrases • Compte tes points",
   outro1="Combien sur 5 ?", outro2="Écris ton score\nen commentaire", items=[
   dict(words=["you", "where", "from", "are"], answer="Where are you from?", fr="D'où viens-tu ?"),
   dict(words=["never", "I", "late", "am"], answer="I am never late.", fr="Je ne suis jamais en retard."),
   dict(words=["like", "I", "coffee", "don't"], answer="I don't like coffee.", fr="Je n'aime pas le café."),
   dict(words=["name", "is", "what", "your"], answer="What is your name?", fr="Comment t'appelles-tu ?"),
   dict(words=["going", "to", "I'm", "the", "market"], answer="I'm going to the market.", fr="Je vais au marché."),
 ]),
 "03_vraifaux": dict(kind="vf", music="mystere", title="VRAI OU FAUX ?", sub="5 phrases • Compte tes points",
   outro1="Combien sur 5 ?", outro2="Écris ton score\nen commentaire", items=[
   dict(s="He go to work every day.", vrai=False, fix="He goes to work…", note="He / She / It : verbe + s"),
   dict(s="Can you explain me this?", vrai=False, fix="Explain this to me", note="Explain something TO someone"),
   dict(s="I am looking forward to seeing you.", vrai=True, fix="", note="Looking forward to + -ing"),
   dict(s="I made a mistake.", vrai=True, fix="", note="On dit MAKE a mistake (pas « do »)"),
   dict(s="My informations are correct.", vrai=False, fix="My information is correct", note="Information n'a pas de pluriel"),
 ]),
 "04_nedis": dict(kind="nedis", music="classique", title="NE DIS PLUS…\nDIS PLUTÔT !", sub="5 fautes que tout le monde fait",
   outro1="Tu faisais laquelle ?", outro2="Dis-le en\ncommentaire", items=[
   dict(wrong="Open the light", right="Turn on the light", note="Allumer = turn on (éteindre = turn off)"),
   dict(wrong="Borrow me your pen", right="Lend me your pen", note="Prêter = lend • Emprunter = borrow"),
   dict(wrong="Say me the truth", right="Tell me the truth", note="Tell + quelqu'un / say + quelque chose"),
   dict(wrong="He is more taller than me", right="He is taller than me", note="Adjectif court : -er (pas « more »)"),
   dict(wrong="I am going to the bed", right="I am going to bed", note="Aller se coucher = go to bed"),
 ]),
 "05_devine": dict(kind="quiz", music="suspense", title="DEVINE LE SENS !", sub="5 expressions anglaises",
   outro1="Combien sur 5 ?", outro2="Écris ton score\nen commentaire", items=[
   dict(q="« It's a piece of cake »", opts=["C'est un bout de gâteau", "C'est très facile", "C'est trop cher"], ok=1, note="Piece of cake = très facile"),
   dict(q="« Break a leg ! »", opts=["Bonne chance !", "Fais attention !", "Casse-toi !"], ok=0, note="Break a leg = bonne chance"),
   dict(q="« I'm all ears »", opts=["Je suis sourd", "J'ai mal aux oreilles", "Je t'écoute"], ok=2, note="All ears = j'écoute attentivement"),
   dict(q="« Hit the books »", opts=["Jeter les livres", "Étudier sérieusement", "Acheter des livres"], ok=1, note="Hit the books = se mettre à étudier"),
   dict(q="« Under the weather »", opts=["Un peu malade", "Sous la pluie", "De mauvaise humeur"], ok=0, note="Under the weather = pas en forme"),
 ]),
 "06_traduis": dict(kind="traduis", music="energie", title="TRADUIS\nSI TU PEUX !", sub="5 phrases du quotidien",
   outro1="Combien sur 5 ?", outro2="Écris ton score\nen commentaire", items=[
   dict(fr="J'ai hâte !", en="I can't wait!", note="Très utilisé à l'oral"),
   dict(fr="Ça fait longtemps !", en="Long time no see!", note="Quand on revoit quelqu'un"),
   dict(fr="Tu me manques.", en="I miss you.", note="Attention : c'est « I » qui manque « you »"),
   dict(fr="Laisse tomber.", en="Never mind.", note="Aussi : « Forget it. »"),
   dict(fr="On y va ?", en="Shall we go?", note="Aussi : « Let's go! »"),
 ]),
 "07_faute": dict(kind="convo", music="mystere", title="TROUVE\nLA FAUTE !", sub="4 conversations • 1 faute dans chacune",
   outro1="Combien sur 4 ?", outro2="Écris ton score\nen commentaire", items=[
   dict(lines=[("Awa", "Hi! How are you?"), ("Koffi", "I'm fine, and you?"), ("Awa", "Fine! Where you are going?")],
        bad=2, fix="Fine! Where are you going?", err="Where you are going", ok="Where are you going"),
   dict(lines=[("Koffi", "Do you like football?"), ("Awa", "Yes, I like it a lot."), ("Koffi", "Me too! I watch every matches.")],
        bad=2, fix="Me too! I watch every match.", err="every matches", ok="every match"),
   dict(lines=[("Awa", "What did you do yesterday?"), ("Koffi", "I have watched a movie yesterday.")],
        bad=1, fix="I watched a movie yesterday.", err="I have watched", ok="I watched"),
   dict(lines=[("Agent", "Can I help you?"), ("Koffi", "Yes, I search the bank.")],
        bad=1, fix="Yes, I'm looking for the bank.", err="I search the bank", ok="I'm looking for the bank"),
 ]),
}
